### ISSUE TITLE
Pip installation fails on Linux & Mac for hawkeslib 2.*

### ISSUE THREAD

**Issue by bmaguireibm** [canerturkmen/hawkeslib#13]
OS: Linux & Mac OS
Python version 2.7 / 3.6 / 3.7 

Pip install results in an error during build leading to an inoperable module.

The error seems to be related to the missing LICENSE file in `hawkeslib.egg-info` dir.

Pip install returns the following error 
```
running install_scripts
  error: [Errno 2] No such file or directory: 'LICENSE'
```
Installation is however successful returning `Successfully installed hawkeslib-0.2.1`, but when importing the module the following error is reported.

`ModuleNotFoundError: No module named 'hawkeslib.util'`

### To Reproduce

`docker run -it  python:3.7  bash -c  'pip install numpy Cython scipy && pip install hawkeslib && python -c "import hawkeslib"'`

Issue only effects version 0.2.1 & 0.2.0.

The following command installs correctly.

`docker run -it  python:3.7  bash -c  'pip install numpy Cython scipy && pip install hawkeslib==0.1.4 && python -c "import hawkeslib"'`

<details><summary>Full log details</summary>
```

Collecting numpy
  Downloading https://files.pythonhosted.org/packages/fc/d1/45be1144b03b6b1e24f9a924f23f66b4ad030d834ad31fb9e5581bd328af/numpy-1.16.4-cp37-cp37m-manylinux1_x86_64.whl (17.3MB)
     |████████████████████████████████| 17.3MB 15.5MB/s 
Collecting Cython
  Downloading https://files.pythonhosted.org/packages/b8/c0/500afce93187b9d94d5c6e80a3032f90bf559bd4c8d12b45a10bc9a67b92/Cython-0.29.10-cp37-cp37m-manylinux1_x86_64.whl (2.1MB)
     |████████████████████████████████| 2.1MB 17.3MB/s 
Collecting scipy
  Downloading https://files.pythonhosted.org/packages/5d/bd/c0feba81fb60e231cf40fc8a322ed5873c90ef7711795508692b1481a4ae/scipy-1.3.0-cp37-cp37m-manylinux1_x86_64.whl (25.2MB)
     |████████████████████████████████| 25.2MB 3.5MB/s 
Installing collected packages: numpy, Cython, scipy
Successfully installed Cython-0.29.10 numpy-1.16.4 scipy-1.3.0
Collecting hawkeslib
  Downloading https://files.pythonhosted.org/packages/31/a6/d409ec06a1f5bf10f23b60ca86b8b2db55a5fd114726486db6004fae1330/hawkeslib-0.2.1.tar.gz
Requirement already satisfied: numpy>=1.14 in /usr/local/lib/python3.7/site-packages (from hawkeslib) (1.16.4)
Requirement already satisfied: Cython>=0.28 in /usr/local/lib/python3.7/site-packages (from hawkeslib) (0.29.10)
Requirement already satisfied: scipy>=1.1 in /usr/local/lib/python3.7/site-packages (from hawkeslib) (1.3.0)
Collecting numdifftools>=0.9 (from hawkeslib)
  Downloading https://files.pythonhosted.org/packages/ab/c0/b0d967160ecc8db52ae34e063937d85e8d386f140ad4826aae2086245a5e/numdifftools-0.9.39-py2.py3-none-any.whl (953kB)
     |████████████████████████████████| 962kB 511kB/s 
Building wheels for collected packages: hawkeslib
  Building wheel for hawkeslib (setup.py) ... error
  ERROR: Complete output from command /usr/local/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-446_7yap/hawkeslib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-hljcdlow --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/hawkeslib
  copying hawkeslib/__init__.py -> build/lib.linux-x86_64-3.7/hawkeslib
  creating build/lib.linux-x86_64-3.7/hawkeslib/model
  copying hawkeslib/model/poisson.py -> build/lib.linux-x86_64-3.7/hawkeslib/model
  copying hawkeslib/model/mv_exp.py -> build/lib.linux-x86_64-3.7/hawkeslib/model
  copying hawkeslib/model/uv_exp.py -> build/lib.linux-x86_64-3.7/hawkeslib/model
  copying hawkeslib/model/model.py -> build/lib.linux-x86_64-3.7/hawkeslib/model
  copying hawkeslib/model/uv_bayes.py -> build/lib.linux-x86_64-3.7/hawkeslib/model
  copying hawkeslib/model/__init__.py -> build/lib.linux-x86_64-3.7/hawkeslib/model
  creating build/lib.linux-x86_64-3.7/hawkeslib/model/c
  copying hawkeslib/model/c/__init__.py -> build/lib.linux-x86_64-3.7/hawkeslib/model/c
  running build_ext
  building 'hawkeslib.model.c.c_uv_exp' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/hawkeslib
  creating build/temp.linux-x86_64-3.7/hawkeslib/model
  creating build/temp.linux-x86_64-3.7/hawkeslib/model/c
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I/usr/local/include/python3.7m -c hawkeslib/model/c/c_uv_exp.cpp -o build/temp.linux-x86_64-3.7/hawkeslib/model/c/c_uv_exp.o -O3 -march=native
  In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                   from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                   from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from hawkeslib/model/c/c_uv_exp.cpp:639:
  /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it with " \
    ^~~~~~~
  g++ -pthread -shared build/temp.linux-x86_64-3.7/hawkeslib/model/c/c_uv_exp.o -L/usr/local/lib -lm -lpython3.7m -o build/lib.linux-x86_64-3.7/hawkeslib/model/c/c_uv_exp.cpython-37m-x86_64-linux-gnu.so
  building 'hawkeslib.model.c.c_mv_exp' extension
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I/usr/local/include/python3.7m -c hawkeslib/model/c/c_mv_exp.cpp -o build/temp.linux-x86_64-3.7/hawkeslib/model/c/c_mv_exp.o -O3 -march=native
  In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                   from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                   from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from hawkeslib/model/c/c_mv_exp.cpp:639:
  /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it with " \
    ^~~~~~~
  hawkeslib/model/c/c_mv_exp.cpp:1958:15: warning: ‘double __pyx_f_9hawkeslib_5model_1c_8c_mv_exp_uu()’ defined but not used [-Wunused-function]
   static double __pyx_f_9hawkeslib_5model_1c_8c_mv_exp_uu(void) {
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  hawkeslib/model/c/c_mv_exp.cpp: In function ‘PyObject* __pyx_pf_9hawkeslib_5model_1c_8c_mv_exp_4mv_exp_fit_em(PyObject*, PyArrayObject*, PyArrayObject*, double, int, double)’:
  hawkeslib/model/c/c_mv_exp.cpp:4788:33: warning: ‘__pyx_v_odll’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     __pyx_t_3 = PyFloat_FromDouble(__pyx_v_odll); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 203, __pyx_L1_error)
                 ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
  g++ -pthread -shared build/temp.linux-x86_64-3.7/hawkeslib/model/c/c_mv_exp.o -L/usr/local/lib -lm -lpython3.7m -o build/lib.linux-x86_64-3.7/hawkeslib/model/c/c_mv_exp.cpython-37m-x86_64-linux-gnu.so
  building 'hawkeslib.model.c.c_uv_bayes' extension
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I/usr/local/include/python3.7m -c hawkeslib/model/c/c_uv_bayes.c -o build/temp.linux-x86_64-3.7/hawkeslib/model/c/c_uv_bayes.o -O3 -march=native
  gcc -pthread -shared build/temp.linux-x86_64-3.7/hawkeslib/model/c/c_uv_bayes.o -L/usr/local/lib -lm -lpython3.7m -o build/lib.linux-x86_64-3.7/hawkeslib/model/c/c_uv_bayes.cpython-37m-x86_64-linux-gnu.so
  building 'hawkeslib.model.c.c_mv_samp' extension
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I/usr/local/include/python3.7m -c hawkeslib/model/c/c_mv_samp.cpp -o build/temp.linux-x86_64-3.7/hawkeslib/model/c/c_mv_samp.o -O3 -march=native
  In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                   from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                   from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from hawkeslib/model/c/c_mv_samp.cpp:639:
  /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it with " \
    ^~~~~~~
  g++ -pthread -shared build/temp.linux-x86_64-3.7/hawkeslib/model/c/c_mv_samp.o -L/usr/local/lib -lm -lpython3.7m -o build/lib.linux-x86_64-3.7/hawkeslib/model/c/c_mv_samp.cpython-37m-x86_64-linux-gnu.so
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/hawkeslib
  creating build/bdist.linux-x86_64/wheel/hawkeslib/model
  copying build/lib.linux-x86_64-3.7/hawkeslib/model/poisson.py -> build/bdist.linux-x86_64/wheel/hawkeslib/model
  copying build/lib.linux-x86_64-3.7/hawkeslib/model/mv_exp.py -> build/bdist.linux-x86_64/wheel/hawkeslib/model
  copying build/lib.linux-x86_64-3.7/hawkeslib/model/uv_exp.py -> build/bdist.linux-x86_64/wheel/hawkeslib/model
  copying build/lib.linux-x86_64-3.7/hawkeslib/model/model.py -> build/bdist.linux-x86_64/wheel/hawkeslib/model
  creating build/bdist.linux-x86_64/wheel/hawkeslib/model/c
  copying build/lib.linux-x86_64-3.7/hawkeslib/model/c/c_uv_exp.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/hawkeslib/model/c
  copying build/lib.linux-x86_64-3.7/hawkeslib/model/c/c_mv_exp.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/hawkeslib/model/c
  copying build/lib.linux-x86_64-3.7/hawkeslib/model/c/__init__.py -> build/bdist.linux-x86_64/wheel/hawkeslib/model/c
  copying build/lib.linux-x86_64-3.7/hawkeslib/model/c/c_uv_bayes.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/hawkeslib/model/c
  copying build/lib.linux-x86_64-3.7/hawkeslib/model/c/c_mv_samp.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/hawkeslib/model/c
  copying build/lib.linux-x86_64-3.7/hawkeslib/model/uv_bayes.py -> build/bdist.linux-x86_64/wheel/hawkeslib/model
  copying build/lib.linux-x86_64-3.7/hawkeslib/model/__init__.py -> build/bdist.linux-x86_64/wheel/hawkeslib/model
  copying build/lib.linux-x86_64-3.7/hawkeslib/__init__.py -> build/bdist.linux-x86_64/wheel/hawkeslib
  running install_egg_info
  running egg_info
  writing hawkeslib.egg-info/PKG-INFO
  writing dependency_links to hawkeslib.egg-info/dependency_links.txt
  writing requirements to hawkeslib.egg-info/requires.txt
  writing top-level names to hawkeslib.egg-info/top_level.txt
  warning: Failed to find the configured license file 'LICENSE'
  reading manifest file 'hawkeslib.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'hawkeslib.egg-info/SOURCES.txt'
  Copying hawkeslib.egg-info to build/bdist.linux-x86_64/wheel/hawkeslib-0.2.1-py3.7.egg-info
  running install_scripts
  error: [Errno 2] No such file or directory: 'LICENSE'
  ----------------------------------------
  ERROR: Failed building wheel for hawkeslib
  Running setup.py clean for hawkeslib
Failed to build hawkeslib
Installing collected packages: numdifftools, hawkeslib
  Running setup.py install for hawkeslib ... done
Successfully installed hawkeslib-0.2.1 numdifftools-0.9.39
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/hawkeslib/__init__.py", line 2, in <module>
    from .model.uv_bayes import BayesianUVExpHawkesProcess
  File "/usr/local/lib/python3.7/site-packages/hawkeslib/model/uv_bayes.py", line 4, in <module>
    from hawkeslib.util.multitrace import MultiTrace
ModuleNotFoundError: No module named 'hawkeslib.util'

```
</details>

**Comment by canerturkmen** [comment]
Hi Brian, that was a rather embarrassing packaging issue. Could you give it a try now?

**Comment by bmaguireibm** [comment]
Hi Caner,  All working on my end now, Thanks a mill 👍
