### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-TFuQ5_/hawkeslib/

### ISSUE THREAD

**Issue by hmfundInD** [canerturkmen/hawkeslib#6]
I get the following error when I try to pip install hawkeslib. My Cython and numpy are up to date. What can I do to solve this issue?

**Comment by hmfundInD** [comment]
Here is the output: 


$ pip install hawkeslib
Collecting hawkeslib
  Downloading https://files.pythonhosted.org/packages/ef/ff/993ae1d87fb259d1404dd7bb12a1b659186e6fd91dfc10850a73d8ae872a/hawkeslib-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Cython>=0.28 and numpy are required. Please install before proceeding
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-CbC3PZ/hawkeslib/

I should note that I'm using an anaconda distribution: 

$ python --version
Python 2.7.12 :: Anaconda 4.2.0 (64-bit)

and the location of both Cython and numpy are in 

~\anaconda2/lib/python2.7/site-packages

**Comment by canerturkmen** [comment]
That's strange, I can't replicate it ..
Could you perhaps try 
```bash
python -c 'from Cython.Build import cythonize'
python -c 'import numpy'
```
to see what you get?

Also perhaps try running
```
which pip
```
to verify it's indeed the right pip that's being used.

Thanks!

**Comment by hmfundInD** [comment]
`$ which pip`
~/anaconda2/bin/pip

**Comment by hmfundInD** [comment]
Here is the output for the python commands:

`$ python -c 'from Cython.Build import cythonize'`
`$ python -c 'import numpy'`
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/peganum/anaconda2/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/peganum/anaconda2/lib/python2.7/site-packages/numpy/core/__init__.py", line 59, in <module>
    from . import numeric
  File "/home/peganum/anaconda2/lib/python2.7/site-packages/numpy/core/numeric.py", line 3093, in <module>
    from . import fromnumeric
  File "/home/peganum/anaconda2/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 17, in <module>
    from . import _methods
  File "/home/peganum/anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py", line 158, in <module>
    _NDARRAY_ARRAY_FUNCTION = mu.ndarray.__array_function__
AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'


I got no output for the first command and an error for the second.

**Comment by hmfundInD** [comment]
Here is the output for the python commands:

`$ python -c 'from Cython.Build import cythonize'`
`$ python -c 'import numpy'`
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/anaconda2/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "~/anaconda2/lib/python2.7/site-packages/numpy/core/__init__.py", line 59, in <module>
    from . import numeric
  File "~/anaconda2/lib/python2.7/site-packages/numpy/core/numeric.py", line 3093, in <module>
    from . import fromnumeric
  File "~/anaconda2/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 17, in <module>
    from . import _methods
  File "~/anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py", line 158, in <module>
    _NDARRAY_ARRAY_FUNCTION = mu.ndarray.__array_function__
AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'


I got no output for the first command and an error for the second.

**Comment by canerturkmen** [comment]
OK it looks like you're having an issue with numpy, probably a system installation of numpy clashing with anaconda e.g. see https://github.com/numpy/numpy/issues/12736 

You could try to start a new environment and install numpy fresh, or (if you're sure no other code depends on an older version)
```
pip install -U numpy
```

Closing as it's not related to the library. Feel free to reopen if it turns into something related to hawkeslib.
