### ISSUE TITLE
ImportError: undefined symbol in c_uv_exp.so

### ISSUE THREAD

**Issue by hmfundInD** [canerturkmen/hawkeslib#7]
Hi, 
I was able to pip install hawkeslib successfully, but I'm unable to import the library in python. Not sure what I can do to resolve this issue.

here is the output:

>>> import hawkeslib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~ /anaconda2/lib/python2.7/site-packages/hawkeslib/__init__.py", line 1, in <module>
    from .model.uv_exp import UnivariateExpHawkesProcess
  File "~ /anaconda2/lib/python2.7/site-packages/hawkeslib/model/uv_exp.py", line 6, in <module>
    from .c.c_uv_exp import uv_exp_ll, uv_exp_ll_grad, uv_exp_sample_ogata, uv_exp_sample_branching, uv_exp_fit_em_base
ImportError: ~/anaconda2/lib/python2.7/site-packages/hawkeslib/model/c/c_uv_exp.so: undefined symbol: _ZTINSt8ios_base7failureB5cxx11E

**Comment by hmfundInD** [comment]
Perfect, it's solved. Thank you.
